[workspace]
members = ["easycar", "info-car-api"]
resolver = "2"

[profile.release]
strip = true # Automatically strip symbols from the binary.
lto = true

[profile.profiling]
inherits = "release"
strip = false
debug = true
